name: 'Workflow Dispatch'
description: 'Trigger another GitHub Actions workflow'

inputs:
  workflow-id: 
    description: 'Id of workflow'
    required: true
  ref: 
    description: 'The reference of the workflow run. The reference can be a branch, tag, or a commit SHA'
    required: true

runs:
  using: 'node12'
  main: 'index.js'