name: 'Workflow Dispatch'
description: 'Trigger another GitHub Actions workflow'

inputs:
  workflow: 
    description: 'Name of workflow to run'
    required: true
  token: 
    description: 'GitHub token with repo write access, can NOT use secrets.GITHUB_TOKEN, see readme'
    required: true    
  inputs:
    description: 'Inputs to pass to the workflow, must be a JSON string.'
    required: false    
  ref:
    description: 'The reference of the workflow run. The reference can be a branch, tag, or a commit SHA'
    required: false
  repo:
    description: 'Repo owner & name, slash separated, only set if invoking a workflow in a different repo'
    required: false    

runs:
  using: 'node12'
  main: 'dist/index.js'
