name: Test Action

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Invoke echo 1 workflow using this action
      uses: ./
      with:
        workflow: Message Echo 1        
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{"message": "blah blah"}'

    - name: Invoke echo 2 workflow using this action
      uses: ./
      with:
        workflow: Message Echo 2        
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Invoke external workflow using this action
      uses: ./
      with:
        workflow: Deploy To Kubernetes           
        repo: benc-uk/dapr-store
        token: ${{ secrets.PERSONAL_TOKEN }}
        ref: master 
   